### ISSUE TITLE
已毕业路过，很赞

### ISSUE THREAD

**Issue by mudong-hu** [ShanQincheng/jmuSupplicant#11]
有个问题，现在锐捷客户端模式相对于e-protal认证模式有什么区别吗，好像在哪里看到protal web验证网速有上限

**Comment by AmadeusGhost** [comment]
客户端认证和网页端认证的限制都是一样的

**Comment by ShanQincheng** [comment]
> 有个问题，现在锐捷客户端模式相对于e-protal认证模式有什么区别吗，好像在哪里看到protal web验证网速有上限

web 认证是我大三那年新推出的，之前只有锐捷客户端。那个时候，我感觉网速没有区别，不知现在怎么样了。这个项目与网页认证的唯一区别就是支持夜间登陆，别的没差。
