### ISSUE TITLE
关于这个项目是否可用在维护

### ISSUE THREAD

**Issue by GnaixEuy** [ShanQincheng/jmuSupplicant#13]
### 错误提示如下：

The login ip in start frame 0.0.0.0
sending eapol start frame
: No such device exists (BIOCSETIF failed: Device not configured)can't live ethernet interface
: No such device exists (BIOCSETIF failed: Device not configured)已发送认证信息，但未收到服务器响应包，请检查网络连接是否正常
且长时间停止响应无法关闭

### 设备信息如下：

设备为 MacBook a1990 macOS 11.2.3  

## 错误截图如下

<img width="650" alt="erro" src="https://user-images.githubusercontent.com/78402118/111446811-bf7cff80-8747-11eb-8055-89dfc94881d4.png">

**Comment by GnaixEuy** [comment]
大佬太强了，就是不知道这个还维护吗还是已经失效了 T_T

**Comment by AmadeusGhost** [comment]
本部是可以用的，你可以手动指定下 ip 看看（教育网 web 认证后去 ip.sb 看下 ipv4 的地址）
另外你的学号和密码暴露了

**Comment by GnaixEuy** [comment]
> 本部是可使用，你可以手动指定ip查看（去ip.sb查看ipv4地址后进行教育网web认证）
> 另外，你的学号和密码被暴露了

感谢大佬，感觉自己软件学的好失败，我再研究研究

**Comment by LGiki** [comment]
这个项目的作者已毕业，但目前应该还能正常使用。
从这个报错信息来看应该是macOS的问题，可以Google搜索一下`BIOCSETIF failed: Device not configured`这个错误相关的解决方案。

**Comment by GnaixEuy** [comment]
> 这个项目的作者已毕业，但目前应该还能正常使用。
> 从这个报错信息来看应该是macOS的问题，可以Google搜索一下`BIOCSETIF failed: Device not configured`这个错误相关的解决方案。

感谢你的回复，我会更换设备来尝试
