### ISSUE TITLE
关于服务器响应包未收到问题

### ISSUE THREAD

**Issue by buxiangtong** [ShanQincheng/jmuSupplicant#14]
![image](https://user-images.githubusercontent.com/108811170/218469572-b8031ec3-b0fe-40ab-9470-36a83d6b416c.png)
您好，请问这个项目当前还有在更新吗？请问以上图片的问题该怎么解决？

**Comment by ShanQincheng** [comment]
你好 buxiangtong。由于时间太久，项目已经基本处于封存状态了，我也没法快速反应出你的问题出现在哪里。
你可以看看本项目 doc 文档下的论文，那是我当年对自己研究的一个完整总结。

没有收到相应包，可能是客户端发送的认证信息( 包长度、内容 )不正确，authenticator 因此不响应导致的。需要抓标准客户端的包，仔细对比长度、内容，可能可以找到原因。

**Comment by D3nesyan** [comment]
在redmi ax6000上亲测可用。可以考虑用路由器试试

**Comment by buxiangtong** [comment]
好的十分感谢
