### ISSUE TITLE
请问下你有关注你之前做教程的那个域名吗？貌似到期了？

### ISSUE THREAD

**Issue by LazX** [ShanQincheng/jmuSupplicant#3]
感觉那个教程还是写的很棒，很详细的！
非常的值得借鉴，而里面提到的一些疑问，我最近也有了自己的一些见解，但是再回去翻找你写的那个教程的时候呢，发现已经打不开了，网站给出的相关提示是，域名租用已经到期，需要用户续费。
我本来是打算整个网页脱机保存下来的，但是现在看起来貌似来不及了？
你能在想想办法？比如续个费什么的~？
 ——十分感谢！

**Comment by LazX** [comment]
po下具体链接地址~~
http://codingstory.com.cn/mo-gai-mentohust-v4ban-ben-de-xin-de/

**Comment by ShanQincheng** [comment]
@LazX 不好意思哦，我已毕业，腾讯云1块钱一个月的福利享受不到了，就没再续费。

之前那篇教程是魔改 mentohust，我认为是浮于表面的学习方法，当时花了很多时间，但没有理解到 802.1X EAP-MD5 协议的核心，不是应该推荐的学习方法。

jmuSuppliant 是我在看了多篇文章（包括但不限于 《RFC3748》，《802.1 X Port-based authentication》），了解了 802.1X EAP-MD5 相关基础知识后，实现的程序。

时间上比魔改稍长，但收获颇丰，我觉得这是我比较推荐的方法。

**Comment by ShanQincheng** [comment]
刚刚上传了我当时的一些思路，供参考。

[锐捷认证过程分析与第三方锐捷认证客户端的设计与实现](https://github.com/ShanQincheng/jmuSupplicant/blob/master/doc/%E9%94%90%E6%8D%B7%E8%AE%A4%E8%AF%81%E8%BF%87%E7%A8%8B%E5%88%86%E6%9E%90%E4%B8%8E%E7%AC%AC%E4%B8%89%E6%96%B9%E9%94%90%E6%8D%B7%E8%AE%A4%E8%AF%81%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%9A%84%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0.pdf)
