### ISSUE TITLE
交叉编译到路由后不断进入混杂模式

### ISSUE THREAD

**Issue by nature2608** [ShanQincheng/jmuSupplicant#7]
![D8E10C2B-7D49-429B-BC01-00C395A6F512](https://user-images.githubusercontent.com/32662472/59175848-9e0ddd80-8b89-11e9-91da-7ae4dd4ab576.png)
会导致系统崩溃，看样子是需要捕获包来发送心跳。

**Comment by ShanQincheng** [comment]
我不清楚进入混杂模式的原因，看日志似乎是程序找不到对应的网卡。日志中有打印“Send an eapol heartbeat freame” ，这应该是已经认证成功，向锐捷交换机保持心跳时才会打印的日志。

为何进入混杂模式的原因可能需要你自己查明，我可能帮助不到你。确认是否认证成功，可以去“集大网络中心”网站，查询你的上网记录。如果可以看到认证成功，说明问题不在认证逻辑，可能是在交叉编译，或者是我的代码无法兼容你的路由器设备。

**Comment by nature2608** [comment]
认证是成功的，进入混杂模式是为了捕获包来算取心跳，而且是需要捕获的时候才进入（每隔20s一个心跳），我看mentohust是进入混杂模式后不退出，一直处于混杂模式，因此不会产生进入退出这个过程。

**Comment by ShanQincheng** [comment]
查了一下，libpcap 库里面，[pcap_open_live() 函数第三个入参表示是否开启混杂模式](https://linux.die.net/man/3/pcap_open_live)，pcap_close() 会关闭网络设备释放资源。 

代码里，函数 send_eap_frame() 中有调用以上两个函数的动作，且给 pcap_open_live() 函数传入的第三个入参是 1（进入混杂模式）。心跳包的定时发送依赖 send_eap_frame() ，这应该是路由器不断进入混杂模式又退出的原因。进入混杂模式，发送心跳包，关闭描述符释放网络设备资源。

混杂模式用来监听经过网络设备的所有数据流，我印象中 jmuSupplicant 是只需要接收发送给自己的数据包就好了，send_eap_frame() 函数中第三个参数传入 1 可能是个 bug。

还有一种可能，就是发送数据包必须开启网络设备的混杂模式，那么 send_eap_frame() 函数在发送完数据包后，就应该及时调用 pcap_close() 函数关闭网络设备释放资源。网络设备进入混杂模式再退出逻辑也是没问题的，使系统崩溃的原因可能仍需排查。具体是否如此我得再查看看。

你可以修改源文件 eap_frames_operations.c 第 298 行 
`pcap_t* descr = pcap_open_live(nic_info.nic_name, SNAP_LENGTH, 1, 1000,  pcap_errbuf);`
修改为：
`pcap_t* descr = pcap_open_live(nic_info.nic_name, SNAP_LENGTH, 0, 1000,  pcap_errbuf);`
即使用非混杂模式获取网络设备资源描述符

修改完成后，重新交叉编译到路由器中运行。如果一切正常，这应该就是一个 bug，麻烦提一个 pull request，谢谢。 @nature2608

**Comment by ShanQincheng** [comment]
还有一种情况，就是发送数据包必须开启网络设备的混杂模式。如果是这样，这段代码就是没有问题的，具体是否如此我得花时间再弄明白。

如果情况是这样，那么 send_eap_frame() 函数在发送完数据包后，就应该及时调用 pcap_close() 函数关闭网络设备释放资源。路由器进入混杂模式再退出逻辑也是没问题的。使系统崩溃的原因可能仍需排查。

**Comment by ShanQincheng** [comment]
查了一会，没有找到混杂模式和 `pcap_inject()  //发送数据帧 ` 函数之间的关联。

找到了两个使用 libpcap 库发送数据帧的例子，[一个开启了混杂模式](https://www.winpcap.org/docs/docs_40_2/html/group__wpcap__tut8.html)，[一个没有开启](http://www.microhowto.info/howto/send_an_arbitrary_ethernet_frame_using_libpcap.html)。供参考。

**Comment by nature2608** [comment]
感谢回答！我大概看了一会，mentohust也是用pcap_open_live函数，而且用法应该是一样的。我还没仔细研究，我先试一下不用混杂模式是否可以成功认证并心跳。在我理解，不知道是否我理解得有问题，在发送心跳时需要捕获success包来计算，而发送包调用时每次都会捕获一次（其实不需要）。我应该在虚拟机下抓包看看才对。

**Comment by ShanQincheng** [comment]
捕获数据包的逻辑在 `capture_eap_frames()` 函数中，`capture_eap_frames()` 函数中有调用 `pcap_open_live()` 函数，获取网络设备描述符并捕获数据包解析认证帧，通过回调函数进入对应的认证步骤。当前代码中是没有开启混杂模式的，也没有必要开启。jmuSupplicant 只需要接受发送给当前网络设备的数据包就好了，没必要开启混杂模式接收其他对于认证无用的数据包。

发送心跳包保持在线，是 `KeepOnline()` 函数中的逻辑。你可以看到，`KeepOnline()`函数仅调用 `send_eap_frame()`来发送心跳包，没有做捕获的动作，不存在捕获一次再发送一次心跳包。

实现逻辑可以通过多看看代码摸清楚，不过我的代码很糟糕可能不是那么容易看懂==

**Comment by nature2608** [comment]
好的，我仔细看看清楚是哪里的原因。谢谢你的回答！我再测试测试，若不会造成死机则不管了。

**Comment by nature2608** [comment]
我已将源码 eap_frames_operations.c 第 298 行改成`pcap_t* descr = pcap_open_live(nic_info.nic_name, SNAP_LENGTH, 0, 1000, pcap_errbuf);` 交叉编译到路由，经测试系统日志没有提示进入离开混杂模式，同时会提示发生心跳包，并且没有掉线。但是我不是jmu的，因此可能与jmu的认证有所不同（我在源码处修改了几处才得以认证成功）。因此可能需要在jmu的同学测试后进一步确定再pull request。谢谢你的细心回答。

**Comment by ShanQincheng** [comment]
OK，路由器系统也不再 crash 了是吗？或许你可以考虑换一个路由器系统哈哈
