### ISSUE TITLE
Ubuntu16.04下正常认证，但交叉编译放到MT7621平台上就会出现bus error

### ISSUE THREAD

**Issue by CChuancey** [ShanQincheng/jmuSupplicant#8]
Ubuntu下编译运行正常，就是心跳包发送的间隔有点不规则，但是不会掉线。

交叉编译工具用的是[openwrt](https://mirrors.tuna.tsinghua.edu.cn/lede/releases/18.06.4/targets/ramips/mt7621/openwrt-sdk-18.06.4-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64.tar.xz)最新的编译工具，libpcap交叉编译的是1.9.0版本。路由器是小米路由3G，运行openwrt最新系统。

在认证时会出现如下问题：

![无标题](https://user-images.githubusercontent.com/37216768/64059444-79a52880-cbef-11e9-9931-e3bcd1a45b0b.png)

**Comment by CChuancey** [comment]
补充：bus error会在收到log success后几秒后发生。这是一个必然发生的错误，无论试多少次。

**Comment by AmadeusGhost** [comment]
我的路由器运行的是openwrt 18.06.1，并无此问题。
你可以试下我编译的，如果依然出现bus error则可以排除编译问题。
链接：http://tmp.link/f/5d6a710fe16f5

**Comment by CChuancey** [comment]
我不是集美大学的学生，由于这个错误是在认证之后出现的，所以我无法使用你提供的进行测试

**Comment by nature2608** [comment]
@AmadeusGhost 不知道是不是iconv的问题？交叉编译到路由通知信息会不显示。或者能否弃用iconv？

 [这个项目](https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk/blob/e88eaf0891c39c62c211294c0435360edf47e5c8/src/mentohust.c)的系统通知处理的比较完美，不知道能否改一下？

**Comment by AmadeusGhost** [comment]
> @AmadeusGhost 不知道是不是iconv的问题？交叉编译到路由通知信息会不显示。或者能否弃用iconv？
> 
> [这个项目](https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk/blob/e88eaf0891c39c62c211294c0435360edf47e5c8/src/mentohust.c)的系统通知处理的比较完美，不知道能否改一下？

通知信息不显示是指那个锐捷通知吗，其实这个问题不大（x
不过有libiconv这个依赖库的话，潘多拉的sdk编译不了，我试试能不能改下。

**Comment by aiamadeus** [comment]
@nature2608 给了我思路，翻了下代码，的确是iconv的问题。
![捕获](https://user-images.githubusercontent.com/42570690/64076713-d17c8600-ccfa-11e9-8799-0f28bf5bac56.PNG)

**Comment by CChuancey** [comment]
能否在非夜间模式下，添加一个掉线重连的功能，感觉arm下不是很稳定。

**Comment by nature2608** [comment]
@AmadeusGhost 那这个iconv能否不使用？而用其他的库？strnormalize.h这个库不知道是否可行？
